### ISSUE TITLE
Delegate to an instance method cannot have null 'this'

### ISSUE THREAD

**Issue by matsujirushi** [jburman/W8lessLabs.Blazor.LocalFiles#6]
Hi @jburman ,
Thanks for produce this library.

I tried [Getting Started steps](https://github.com/jburman/W8lessLabs.Blazor.LocalFiles#getting-started) in README.md, I got below error.

**Console:**
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Delegate to an instance method cannot have null 'this' (Parameter 'this')
System.ArgumentException: Delegate to an instance method cannot have null 'this' (Parameter 'this')
   at uf2.Pages.Counter.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

If button go through the private method, no error.

**Code:**
```
<button @onclick="@SelectFiles">Select Files</button>
@code {
    void SelectFiles()
    {
        fileSelect.SelectFiles();
    }
}
```

**Comment by PhotoAtomic** [comment]
same issue here: I can't figure out what is causing it.
If I remove the assignment in the tag attribute then everything works

**Comment by jburman** [comment]
Ahh sorry about that. The example was bad because the fileSelect component reference is not initialized the first time the page renders.  So <button @onclick="**fileSelect**.SelectFiles"> was throwing the error.  I've updated the example on the README.
